concave_points_mean= "concave points_mean"n;
Label concave_points_mean='concave points_mean';
drop "concave points_mean"n;
concave_points_se= "concave points_se"n;
Label concave_points_se='concave points_se';
drop "concave points_se"n;
concave_points_worst= "concave points_worst"n;
Label concave_points_worst='concave points_worst';
drop "concave points_worst"n;
